### ISSUE TITLE
Außelhalb breich click get close

### ISSUE THREAD

**Issue by Faldebbagh** [TR-RBM/RobotGUI#6]
wenn in Außerhalb den Breich gedruckt wurde, lifert eine Fehler zurück 
Traceback (most recent call last):
  File "E:\Feras\Documents\RobotGUI\main.py", line 447, in <module>
    main()
  File "E:\Feras\Documents\RobotGUI\main.py", line 443, in main
    main_window = window(win,screen_x,screen_y, log)
  File "E:\Feras\Documents\RobotGUI\main.py", line 80, in __init__
    self.KI_path_finder()
  File "E:\Feras\Documents\RobotGUI\main.py", line 360, in KI_path_finder
    if int(_start[1]) > int(_ziel[1]): # wenn zahl ist gröber. verkleinern
IndexError: string index out of range

**Comment by TR-RBM** [comment]
Werde heute weiter versuchen das Problem zu lösen.
Habe schon eine Idee zur umsetztung aber mal schauen.
Desweiteren werde ich meine Testergebnisse auf Tim-Test hochladen, sowie das letzte update.

**Comment by TR-RBM** [comment]
Konnte durch ein Update verhindern das das Script crashed, aber es verhält sich noch sehr komisch wenn man außerhalb des Bereiches drückt.
